'\" t
.\"     Title: webserv
.\"    Author: Team Web server 42
.\" Generator: Asciidoctor 2.0.18
.\"      Date: 2023-04-20
.\"    Manual: WEBSERV
.\"    Source: WEBSERV
.\"  Language: English
.\"
.TH "WEBSERV" "8" "2023-04-20" "WEBSERV" "WEBSERV"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
webserv \- the basic HTTP web server
.SH "SYNOPSIS"
.sp
\fBwebserv\fP FILE
.SH "CONFIGURATION FILE"
.sp
The configuration file is in JSON format. You have to define the port and the path on your website
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Simple example
.RE
.sp
.if n .RS 4
.nf
.fam C
{
  "port" : 6060,
  "path" : "/path/of/test/website"
}
.fam
.fi
.if n .RE
.SH "EXIT STATUS"
.sp
\fB0\fP
.RS 4
Success.
.RE
.sp
\fB1\fP
.RS 4
Failure.
.RE
.SH "RESOURCES"
.sp
\fBGitHub repository:\fP \c
.URL "https://github.com/t\-h2o/webserv" ""
.br
\fBProject web site:\fP \c
.URL "https://t\-h2o.github.io/webserv" "" ""
.SH "AUTHOR"
.sp
Team Web server 42