= Web server
:sectnums:
:nofooter:
:toc: left

== Web server UML diagram

=== Usecase diagram

[plantuml, target=usecase, format=svg, width=60%]
....
left to right direction
actor Client as client
package "Web server" as wbs {
  usecase "Web site" as ws
}
client --> ws
....

=== Sequence diagram

[plantuml, target=sequence, format=svg, width=60%]
....
Client -> "Web server": request
"Web server" -> Client: response
....

=== Activity diagram

[plantuml, target=activity, format=svg, width=60%]
....
start
:parses json file;
:main loop;
....

=== Component diagram

[plantuml, target=component, format=svg, width=60%]
....
Component "Files of the website\n(/var/www)" as www
Component "Common Gateway Interface\n(CGI)" as cgi
Component "Client\n(browser firefox)" as client
component "Web server" as wbs
....

=== State diagram

[plantuml, target=state, format=svg, width=60%]
....
state "parses json file" as pjf
state "main loop" as loop
[*] --> pjf : start
pjf --> loop : success
pjf --> [*] : failed
....

== JSON parser

=== Class diagram

[plantuml, target=json_class, format=svg, width=60%]
....
class Config {
  == private attribute ==
  std::map<std::string, value *> _config
}

class Value {
  == private attribute ==
  std::string _value
}

class Json {
  == static method ==
  Config *read(char *path)
}
....

=== State diagram

[plantuml, target=json_state, format=svg, width=60%]
....
state "open file" as of
state "close file" as cf
state "read line" as rl
state "process line" as pl

[*] --> of : start
of --> [*] : failed
of --> rl
rl --> pl
rl --> cf : EOF
pl --> rl
pl --> [*] : failed
cf --> [*]
....

=== Object diagram example

[plantuml, target=json_object, format=svg, width=60%]
....

map "map<String, Value *>" as charlie_address {
 "street" => "Brooklin"
 "street_number" => 1
}

map "map<String, Value *>" as config {
 "name" => "Alice"
 "age" => 42
 "address" *-> charlie_address
}
....

== Resources

=== Tools

* Create UML diagram with https://plantuml.com/[plantUML]

=== JSON parsing

* wikipedia: https://en.wikipedia.org/wiki/JSON[JSON]
* json.org: https://www.json.org/json-en.html[diagram]
